micronaut:
  application:
    name: k1te-auth
  router:
    static-resources:
      css:
        mapping: /css/*.css
        paths: classpath:static/css
      js:
        mapping: /js/*.js
        paths: classpath:static/js
      swagger:
        mapping: /swagger/**
        paths: classpath:META-INF/swagger
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  security:
    reject-not-found: true
    authentication: cookie
    redirect:
      login-success: /profile
      login-failure: /auth/login?failed=true
      logout: /auth/login
      prior-to-login: true
      unauthorized:
        url: /auth/login
    intercept-url-map:
      - pattern: /css/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /js/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
    token:
      cookie:
        cookie-http-only: true
        cookie-secure: true
        cookie-same-site: strict
        cookie-max-age: 1h
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
              jws-algorithm: HS256
    csrf:
      signature-key: ${CSRF_SIGNATURE_KEY}
      cookie-name: csrfToken
      cookie-http-only: true
      cookie-secure: true
      cookie-same-site: strict
      cookie-max-age: 1h
      filter:
        regex-pattern: "^(?!(/login|/logout|/auth/.*|/oauth2/token|/oauth2/userinfo)$).*$"
  views:
    csp:
      enabled: true
      policy-directives: >-
        default-src 'self';
        script-src 'self' 'sha256-HZbM5aZPE0t7sUAGF95thuZ6hV0Z1HDVee1M4aBPjW4=' 'sha256-dk5tS6x3KBnHeLdk1MrElwfehYsePagQhx25cy/CaEI=' https://challenges.cloudflare.com https://unpkg.com/@hotwired/turbo@8.0.11/dist/turbo.es2017-umd.js;
        style-src 'self' 'sha256-RL3ie0nH+Lzz2YNqQN83mnU0J1ot4QL7b99vMdIX99w=' 'sha256-WAyOw4V+FqDc35lQPyRADLBWbuNK8ahvYEaQIYF1+Ps=' 'sha256-ThOZ6uA061m+uFm4SBBZk00gmID2mIz7KZPk50Wjjho=' https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css;
        img-src 'self' data: https://picocss.com/favicon.ico;
        frame-src 'self' https://challenges.cloudflare.com; frame-ancestors 'none'
  email:
    from:
      email: ${SENDER_EMAIL}
      name: ${SENDER_NAME}
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
endpoints:
  prometheus:
    sensitive: false
smtp:
  auth: ${SMTP_AUTH}
  starttls:
    enable: ${SMTP_STARTTLS_ENABLE}
  session:
    username: ${SMTP_SESSION_USERNAME}
    password: ${SMTP_SESSION_PASSWORD}
  host: ${SMTP_HOST}
  port: ${SMTP_PORT}
turnstile:
  siteKey: ${TURNSTILE_SITE_KEY}
  secretKey: ${TURNSTILE_SECRET_KEY}
admin:
  name: ${ADMIN_NAME}
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
server:
  url: ${SERVER_URL}
pem:
  path: ${PEM_FILE_LOCATION:`.key-pair/ec512-key-pair.pem`}
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/postgres`}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: none
    packages-to-scan:
      - 'pragmasoft.k1teauth'
flyway:
  datasources:
    default:
      enabled: true
      placeholders:
        server-url: ${server.url}
        admin-name: ${admin.name}
        admin-email: ${admin.email}
        admin-password: ${admin.password}
cache:
  capacity: 1000
bucket:
  capacity: 10
  refillRate: 1s
